### ISSUE TITLE
Rate limit applied to public methods

### ISSUE THREAD

**Issue by wklm** [discosultan/KrakenCore#1]
Hey, many thanks for this wrapper!
Could you tell me please, what is the reason for applying rate limit for anonymous public methods calls like `https://api.kraken.com/0/public/Time` if the api itself doesn't limit it?

Cheers,
Wojtek

**Comment by discosultan** [comment]
Hey @wklm!

Rate limit still applies to public API. However, it is not tied to your account, but rather your IP address is used for tracking. The limit is 1 call per second.

-----

I was in contact with their support to figure this one out, as their documentation was vague in that regard. Below is the conversation:

**Question**
> The documentation found at https://support.kraken.com/hc/en-us/articles/206548367 is unclear in some aspects:
>
> - For non-authenticated calls (Public API), what's considered a distinct "user"? Which tier's rate applies to those calls? Or does the call rate limit not apply in this case?
>
> Best regards,
> Jaanus

**Response**
> Totally understand:
>
> - For non-authenticated calls (Public API), what's considered a distinct "user"?
>
> For Public API Methods we use your IP Address to determine you as a distinctive user.
>
> - Or does the call rate limit not apply in this case?
>
> We have a limit of 1 call per second for public methods - your tier rate limits only apply to private methods such as querying trades and balances. Hope this helps.
>
> Best Regards, 
> Johnny
>
> Kraken Client Engagement Team

-----

Obviously things might have changed meanwhile.

**Comment by discosultan** [comment]
Closing this now - feel free to ping, @wklm, if you have additional questions or think it's a problem- I'll reopen the issue.
