### ISSUE TITLE
Add raw result to Kraken api call response

### ISSUE THREAD

**Issue by romeop555** [discosultan/KrakenCore#5]
Hi, i'm developing a trading engine which is working with my own kraken client and i'd like to adopt this project!
First implementation i need i to have a raw response from the kraken api calls, because for example every 4 hours i save the file obtained in order to have weeks of data ready for backtesting.
For this reason if you agree i will do a PR with these implementations in bold italic

-in KrakenREsponse.cs

```csharp
/// <summary>
/// Gets or sets the raw result of a request.
/// </summary>
public string Response { get; set; }
```

-in KrakenClient.cs

```csharp
private async Task<KrakenResponse<T>> SendRequest<T>(HttpRequestMessage req, RateLimiter rateLimiter, int cost)
{
    // ...

    // Deserialize response.
    string jsonContent = await res.Content.ReadAsStringAsync().ConfigureAwait(false);
    var result = JsonConvert.DeserializeObject<KrakenResponse<T>>(jsonContent, JsonSettings);
    result.Response = jsonContent;

    // ...
}
```

**Comment by discosultan** [comment]
Hi, @romeop555 

I don't see any issues with that currently. We have the raw json string in memory already, so why not. Only downside I could come up with is if we later wanted to move to a streaming deserialization, it might incur unnecessary overhead.

Anyway, I'd be happy to merge the PR. But perhaps be even more explicit and name the property `RawJson` or something similar. Reading the following feels unintuitive:

```cs
KrakenResponse<TradeBalanceInfo> response = await client.GetTradeBalance();
Console.WriteLine(response.Response);
```

**Comment by discosultan** [comment]
Fixed by https://github.com/discosultan/KrakenCore/commit/f35f2ef327a54be60eaee1a4f54358cedac09258
