### ISSUE TITLE
AddStandardOrder not working?

### ISSUE THREAD

**Issue by flaghub** [discosultan/KrakenCore#6]

**Comment by flaghub** [comment]
Hi,

Thank-you for your project It's really helpful.

I suceeded to use a lot of your methods...Except one

`        private static async Task TradeAsync(KrakenClient client)
        {

            string pair = "LTCEUR";
            string type = "sell";
            string orderType = "limit";
            decimal volume = 0.0001m;
            decimal price = 80; 

            try
            {
                var response = await client.AddStandardOrder(pair, type, orderType, volume, price);

                if (response.Errors.Count() == 0)
                {
                    Console.Write("OK:" + response.Result.Description.Order);
                }
                else
                {
                    Console.Write("Error:" + response.Errors.First().Value);
                }
            }
            catch (HttpRequestException httpExc)
            {
                Console.WriteLine("httpExc:" + httpExc.Message);
            }
            catch (KrakenException kExc)
            {
                Console.WriteLine("kExc:" + kExc.Message);
            }
            catch (Exception exc)
            {
                Console.WriteLine("Exc:" + exc.Message);
            }
        }`

I know there's a lot of downtime with kraken but here I only get this message:

> There was a problem with a response from Kraken

Any idea what could be the problem?

Thank you

**Comment by flaghub** [comment]
OK sorry I haven't seen the Exception.Errors properties...
The message was "Invalid arguments:volume"
And yes that was a stupid error because LTC min volume is 0.1 ....

Well now I have another problem :(

> EService:Unavailable
If you look on the [kraken doc](https://support.kraken.com/hc/en-us/articles/115014409247-Order-may-have-failed-EService-Unavailable): It says that It may occurs when API response time si above 2.000ms.
Well It looks like It's always > 2000ms

What I don't understand is why do we get this error only with the AddStandardOrder? Other methods seems to work.

Any piece of advice to make sure an order is processed?

**Comment by discosultan** [comment]
@flaghub Closing this for now as I'm fairly certain it's an issue on Kraken's side. Feel free to leave a comment if you still think it's an issue with this library and I'll reopen the issue.
