### ISSUE TITLE
AddStandardOrder with expiretime +<n> not working

### ISSUE THREAD

**Issue by nooxnet** [discosultan/KrakenCore#8]
AddStandardOrder does not work if the parameter expireTime (expiretime) is e.g. +60.

It seems like the parameters are applied via query string. So I assume they should be urlencoded. And as space were urlencoded as '+' the '+' is probably interpreted as a space.

So I think in KrakenClient the UrlEncode method should actually urlencode the Value. I did not want to have side effects so I just added:

`args.Where(x` => x.Value != null).Select(x => x.Key + "=" + x.Value.Replace("+", "%2B"))

**Comment by discosultan** [comment]
@nooxnet Thanks for the report! I think you are spot on and this is something not covered by the tests. I'll try to push a fix as soon as Kraken services are back online to validate.

**Comment by discosultan** [comment]
Fixed by https://github.com/discosultan/KrakenCore/commit/6147afa9f7c6ba6ca38c2dee65102594cacb6fe6
